// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddUserSegments implements pgx.CopyFromSource.
type iteratorForAddUserSegments struct {
	rows                 []AddUserSegmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddUserSegments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddUserSegments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].SegmentID,
		r.rows[0].RemoveAt,
	}, nil
}

func (r iteratorForAddUserSegments) Err() error {
	return nil
}

func (q *Queries) AddUserSegments(ctx context.Context, arg []AddUserSegmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_segments"}, []string{"user_id", "segment_id", "remove_at"}, &iteratorForAddUserSegments{rows: arg})
}
